### ISSUE TITLE
Error: No named parameter with the name 'materialTapTargetSize'.

### ISSUE THREAD

**Issue by xiejibiao** [firatcetiner/scrollable_list_tabview#1]
When I use the plug-in, the following error occurs

Compiler message:
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.4/lib/scrollable_list_tabview.dart:105:25: Error: No named parameter with the name 'materialTapTargetSize'.
                        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                        ^^^^^^^^^^^^^^^^^^^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/packages/flutter/lib/src/material/outline_button.dart:62:9: Context: Found this candidate, but the arguments don't match.
  const OutlineButton({
        ^^^^^^^^^^^^^
Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.12.6 16G29, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 9.0)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by firatcetiner** [comment]
Sorry for the inconvenience. I just released version `0.1.5` of `scrollable_list_tabview` and it should fix this issue.

**Comment by xiejibiao** [comment]
> Sorry for the inconvenience. I just released version `0.1.5` of `scrollable_list_tabview` and it should fix this issue.

Thank you very much for fixing the exception.

I have a new exception after using version 0.1.5
/// ---------------------------------------------------------------------------------------------------------

Compiler message:
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:100:68: Error: Method not found: 'MaterialStateProperty.all'.
                            foregroundColor: MaterialStateProperty.all(
                                                                   ^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:102:68: Error: Method not found: 'MaterialStateProperty.all'.
                            backgroundColor: MaterialStateProperty.all(selected
                                                                   ^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:106:57: Error: Method not found: 'MaterialStateProperty.all'.
                            side: MaterialStateProperty.all(BorderSide(
                                                        ^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:110:62: Error: Method not found: 'MaterialStateProperty.all'.
                            elevation: MaterialStateProperty.all(0),
                                                             ^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:111:58: Error: Method not found: 'MaterialStateProperty.all'.
                            shape: MaterialStateProperty.all(
                                                         ^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:98:30: Error: The method 'OutlinedButton' isn't defined for the class '_ScrollableListTabViewState'.
 - '_ScrollableListTabViewState' is from 'package:scrollable_list_tabview/scrollable_list_tabview.dart' ('/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart').
Try correcting the name to the name of an existing method, or defining a method named 'OutlinedButton'.

                      child: OutlinedButton(
                             ^^^^^^^^^^^^^^
/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart:99:32: Error: The method 'ButtonStyle' isn't defined for the class '_ScrollableListTabViewState'.
 - '_ScrollableListTabViewState' is from 'package:scrollable_list_tabview/scrollable_list_tabview.dart' ('/Users/xjb/Desktop/DevelopmentToot/flutter_1.17.5/.pub-cache/hosted/pub.flutter-io.cn/scrollable_list_tabview-0.1.5/lib/scrollable_list_tabview.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ButtonStyle'.
                        style: ButtonStyle(
                               ^^^^^^^^^^^

**Comment by firatcetiner** [comment]
Please make sure that you are using the latest version of Flutter. I cannot reproduce this issue with example application.
