### ISSUE TITLE
Is it possible to set the background color of the tab?

### ISSUE THREAD

**Issue by johnareid54** [firatcetiner/scrollable_list_tabview#12]
The background color of the tab header seems to be set to white - it is possible to define what color to use?![image](https://user-images.githubusercontent.com/53974881/137095968-76795bd9-9a1c-435b-8a27-8a7a2482d452.png)
Sample image supplied.

**Comment by thanhhuy0611** [comment]
Same the question, any update??

**Comment by thanhhuy0611** [comment]
@johnareid54 I found a way to work around it, you can change the property `cardColor` in your app theme.

**Comment by johnareid54** [comment]
Thanks @thanhhuy0611 it works!

**Comment by johnareid54** [comment]
Rather than changing the app theme, you can put the theme before the widget - i.e.:

`Theme(
              data: ThemeData(cardColor: Colors.transparent),
              child: ScrollableListTabView(
                tabHeight: 36,
                tabs: [
                  scrollTab("0 - 19", 0, 20),
                  scrollTab("20 - 39", 20, 40),
                  scrollTab("40 - 59", 40, 60),
                  scrollTab("60 - 79", 60, 80),
                  scrollTab("80 - 100", 80, 101),
                ],
              ),
            ),`
