### ISSUE TITLE
Use inside column or custom scroll view

### ISSUE THREAD

**Issue by evanholt1** [firatcetiner/scrollable_list_tabview#7]
Hello!
this package seems to fit exactly on a screen i have to make. Unfortunately, in the screen there will also be some content before the list (an image and text below it), and thus i need to use a column. Also, the entire page needs to be scrollable in one go.However, this package only works when used as the body of a page. 
Is there any way i can use ScrollableListTabView inside a column or custom scrollview? meaning not as the entire body of a screen?

**Comment by firatcetiner** [comment]
You can use it inside a Column like this:

```
Column(
  Text('A component'),
  Expanded(ScrollableListTabView(),),
),
```
The key is to wrap ScrollablelistTabView with a `Flexible`. If you don't want the ScrollableListTabView to fill the entire viewport, you can give it a specific size by wrapping it with a SizedBox or a similar widget.

However, you can't use it in a Scrollable widget as it breaks the purpose/functionality of the ScrollableListTabView when you have an ancestor Scrollable widget.

**Comment by evanholt1** [comment]
Sorry for the late reply!
This did work as expected. Thanks a lot.
I would also like to point out that when using slivers (as i had to switch to that in the end because of a different widget),
ScrollableListTabView() works well inside SliverFillRemaining().
